//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordPlay.Content.Words {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordPlay.Content.Words.WordsResource", typeof(WordsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWESOME,MEOWS,WAMES,WOMAS,MAWS,MEOW,MEWS,MOWS,SAWM,SMEW,SWAM,WAMES,WOMA,AWEE,AWES,EMES,EMOS,EWES,MAES,MESA,MOAS,OWES,OWSE,SAME,SEAM,SEEM,SEME,SOMA,SOME,WAES,WEES,WOES,EASE,MAW,MEW,MOW,MWA,AWE,EME,EMO,EMS,EWE,MAE,MAS,MEA,MOA,MOS,OMS,OWE,SAW,SEW,SOM,SOW,WAE,WAS,WEE,WOE,WOS,AES,ESE,OES,OSE,SAE,SEA,SEE.
        /// </summary>
        internal static string Awesome {
            get {
                return ResourceManager.GetString("Awesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEETAH,CHETAH,THECAE,CHETH,HATCH,HEATH,CHEAT,TACHE,TEACH,THECA,HATH,HETH,ACHE,CHAT,EACH,ECHE,ECHT,ETCH,TACH,TECH,EATH,HAET,HATE,HEAT,THAE,THEE,CATE,CETE,TACE,HAH,HEH,ETH,HAE,HAT,HETH,THE,ACE,ACT,CAT,CEE,TEC,ATE,EAT,ETA,TAE,TEA,TEE.
        /// </summary>
        internal static string Cheetah {
            get {
                return ResourceManager.GetString("Cheetah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROOKED,COOKED,CORKED,DOCKER,REDOCK,ROCKED,COOKER,RECOOK,ROOKED,COKED,DRECK,CROOK,OCKER,DROKE,CODER,COOED,CORED,CREDO,DECOR,COOER,RODEO,DECK,DOCK,COKE,COOK,CORK,RECK,ROCK,DORK,DREK,KORE,ROOK,CODE,COED,CORD,CRED,DECO,CERO,CORE,DOER,DOOR,DORE,ODOR,ORDO,REDO,RODE,ROOD,KOR,OKE,COD,DOC,COO,COR,ECO,ORC,REC,ROC,DOE,DOR,ODE,RED,ROD,ORE,ROE,ROO.
        /// </summary>
        internal static string Crooked {
            get {
                return ResourceManager.GetString("Crooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOLPHIN,POIND,DHONI,INDOL,HOLP,PHON,PLOD,POND,DHOL,HIND,HOLD,PION,HONI,DINO,DIOL,IDOL,LIDO,LINO,LION,LOID,LOIN,NODI,NOIL,NOLI,OLID,HIP,HOP,PHI,PHO,DIP,DOP,LIP,LOP,NIP,PIN,POD,POL,DOH,HID,HIN,HOD,HON,NOH,POI,DIN,DOL,DON,HOI,LID,LIN,NIL,NOD,OLD,ION,OIL.
        /// </summary>
        internal static string Dolphin {
            get {
                return ResourceManager.GetString("Dolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GODDESS,DODGES,DOSSED,DODGE,DOGES,DOSED,DOSES,GESSO,SEGOS,DOGE,DOGS,EDDO,GEDS,GODS,ODDS,DOES,DOSE,DOSS,EGOS,GOES,ODES,SEGO,SEGS,SODS,OSES,DOG,GED,GOD,ODD,DOE,DOS,EDS,EGO,GOS,ODE,ODS,SEG,SOD,ESS,OES,OSE,SOS,.
        /// </summary>
        internal static string Goddess {
            get {
                return ResourceManager.GetString("Goddess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNEY,ENJOY,YOURN,ONERY,YOURE,ROUEN,JURY,JOEY,JEON,JOUR,JURE,YOUR,OYER,RUNE,YORE,EURO,NERO,ONER,RONE,ROUE,JOY,JUN,JEU,JOE,RYU,YEN,YON,YOU,RUN,RYE,URN,YER,EON,ERN,NOR,ONE,OUR,RUE,OER,ORE,REO,ROE,.
        /// </summary>
        internal static string Journey {
            get {
                return ResourceManager.GetString("Journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KITCHEN,ETHNIC,CHINK,KENCH,KETCH,THICK,THINK,CHINE,KITHE,NICHE,TENCH,ETHIC,THEIN,THINE,HECK,HICK,NECK,NICK,TICK,CHIN,HIKE,INCH,KHET,KITH,CHIT,ECHT,ETCH,ITCH,KENT,KINE,KNIT,TECH,TICH,CENT,CINE,KITE,NICE,TIKE,CITE,ETIC,HENT,HINT,THEN,THIN,NITE,TEIN,TINE,ICK,KHI,CHI,HIC,ICH,INK,KEN,KIN,NEK,TCH,KIT,HEN,HIN,ICE,NTH,TIC,ETH,HET,HIE,HIT,THE,NET,NIT,TEN,TIN,TIE.
        /// </summary>
        internal static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYSTERY,STYMY,TREYS,TYERS,TYRES,TERMS,TREMS,EYRY,RYES,STEY,STYE,TREY,TYER,TYES,TYRE,REMS,STEM,TERM,TREM,ERST,REST,RETS,TRES,RYE,STY,TRY,TYE,YER,YES,YET,EMS,MES,MET,REM,ERS,EST,RES,RET,SER,SET,TES.
        /// </summary>
        internal static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCIENCE,SCENIC,NIECES,CENSE,CINES,NIECE,SCENE,SINCE,SEINE,CINE,NICE,CEES,ICES,SICE,ESNE,SEEN,SENE,SINE,CEE,CIS,ICE,SEC,SIC,ENS,INS,NEE,SEN,SIN,ESE,SEE,SEI.
        /// </summary>
        internal static string Science {
            get {
                return ResourceManager.GetString("Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIFORM,INFORM,FORUM,MINOR,MOURN,ONIUM,FIRM,FORM,FROM,FINO,FIRN,FOIN,FOUR,INFO,MORN,MUNI,MUON,NORM,INRO,IRON,NOIR,NORI,RUIN,FIN,FIR,FON,FOR,FOU,FRO,FUN,FUR,RIF,MIR,MOI,MON,MOR,MUN,NIM,NOM,RIM,ROM,RUM,ION,NOR,OUR,RIN,RUN,UNI,URN.
        /// </summary>
        internal static string Uniform {
            get {
                return ResourceManager.GetString("Uniform", resourceCulture);
            }
        }
    }
}
